### ISSUE TITLE
Syntax Issue 

### ISSUE THREAD

**Issue by iam-veeramalla** [SamyakSheokar2203/AWS-Resouce-Tracker#1]
Looks like there is a syntax issue at line 28. Could be a typo.

https://github.com/SamyakSheokar2203/AWS-Resouce-Tracker/blob/5fd1d1dfdf6b04bffa6946897b4828ba73f343f7/AWS-Resource-Tracker.sh#L28

**Comment by SamyakSheokar2203** [comment]
Thank you so much for finding the mistake... I solved it
